#!/usr/bin/env bash
# transfer a file from client to a server

if [[ "$#" -gt 2 ]]
then
    file_tr=$1
    user=$3"@"$2
    prev_key=$4

    scp -i "$prev_key" -o StrictHostKeyChecking=no "$file_tr" "$user":~/
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
