#!/usr/bin/env bash
# allow Nginx to connect through port 80

sudo ufw allow 'Nginx HTTP'
html="
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Holberton School for the win!</h1>
</body>
</html>
"
echo "$html" >>  /var/www/html/index.nginx-debian.html
