#!/usr/bin/env bash
# Displays the content of the file /etc/passwd
# only username, user id, and home directory path for the user

filename="/etc/passwd"
while read -r line
do
    echo "$line" | cut -d ':' -f 1,3,6
done<"$filename"
