#!/usr/bin/env bash
# This displays holberton school and loop is at 4 display bad luck for china,
# when on 9 bad luck Japan, and 17 bad luck for Italy

MAXCOUNT=20
count=1
while [ "$count" -le $MAXCOUNT ]
do
    echo "$count"
    case "$count" in
	 4) echo "bad luck from China";;
	 9) echo "bad luck from Japan";;
	 17) echo "bad luck from Italy";;
    esac
	(( count += 1 ))
done
