#!/usr/bin/env bash
# This displays holberton school and loop is at 4 display bad luck for china,
# when on 9 bad luck Japan, and 17 bad luck for Italy

MAXCOUNT=20
count=1
while [ "$count" -le $MAXCOUNT ]
do
	echo "$count"
	if [ "$count" -eq 4 ]
	then
		echo "bad luck from China"
	elif [ "$count" -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ "$count" -eq 17 ]
	then
		echo "bad luck from Italy"
	fi
	(( count += 1 ))
done